Added frame onclick collapsing
raylu/traceface pull request #4
Opened 2017-11-19 04:20 UTC by ebracho

Just an idea to make larger stack traces easier to navigate.

2017-11-19 07:50 UTC, raylu requested changes
I was really caught up in making frames collapse all of their children when I tried to implement this, but I think this is nicer than without any collapsing.

would be really need to have an "expand all" button though... (though I'm happy to merge without)

2017-11-19 07:50 UTC, raylu commented on style.css
> +div.frame table {
can we combine these into
```css
div.frame code, div.frame table {
```

2017-11-19 07:50 UTC, raylu commented on collapse.js
> +	let frames = document.getElementsByClassName('frame');
this should be `const`

2017-11-19 07:50 UTC, raylu commented on collapse.js
> +window.onload = function() {
can we make this `'use strict';`?

2017-11-19 07:50 UTC, raylu commented on collapse.js
> +		frames[i].onclick = function(event) {
can we use `addEventListener`?

2017-11-19 07:50 UTC, raylu commented on collapse.js
> +	for (let i = 0; i < frames.length; i++) {
this can be [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

2017-11-19 07:50 UTC, raylu commented on collapse.js
> +			this.children[2].style.display = this.children[2].style.display === 'block' ? 'none' : 'block'
this can be
```js
const code = this.querySelector('code');
const table = this.querySelector('table');
code.style.display = ...
```

2017-11-19 08:11 UTC, ebracho commented
Collapsing all children might be tricky with a nested structure built into the DOM elements. I'll see if I can think of something. 

My client-side js is pretty rusty, thanks for the tips.

2017-11-19 08:50 UTC, raylu commented
yeah, I concluded we'd need to completely change the thing we pass into the template to do collapsing children, which is why I gave up. but I think what you have here is better than no collapsing at all

2017-11-19 08:52 UTC, raylu commented
final ask: can you squash these commits? (`git rebase -i master`)

2017-11-19 09:28 UTC, ebracho commented
I think that [Node.nextSibling](https://developer.mozilla.org/en-US/docs/Web/API/Node/nextSibling) and a little cleverness might do the trick for toggling child frames.

2017-11-19 18:52 UTC, ebracho commented
I'm not sure exactly what the best behavior would be, but I modified toggleFrame to apply the same action to all of it's child frames. Is this what you were going for?

2017-11-19 19:32 UTC, raylu commented
that... could work. if we're going with the parsing-depth route (I tried this but abandoned it - don't remember why), we probably want to modify the template to add a `data-depth="2"` attr to the tag so we don't have to parse the padding. at least, that's how I did it in my abandoned version

2017-11-19 19:59 UTC, ebracho commented
I like that approach. The solution I wrote only depends on relative depth of frames, so parsing the padding was enough. But adding a `data-depth="2"` tag opens up a whole bunch of other options.

2017-11-19 20:35 UTC, raylu commented on frames.js
> +	collapseAllButton.addEventListener('click', collapseAllFrames);
you can write these as
```js
expandAllButton.addEventListener('click', (event) => {
    setAllFrameStates('expand');
});
```

2017-11-19 20:35 UTC, raylu commented
could you squash either everything after the first commit or everything again?

2017-11-19 20:37 UTC, raylu commented on frames.js
> +	let childFrames = [];
we modify the array but not the ref, so this can also be `const`

2017-11-21 05:28 UTC, raylu approved these changes

2017-11-21 05:28 UTC, merged